/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT1_10 (number 4), POS_S1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_POS_S1_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_POS_S1_GPIO_PIN 10U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_POS_S1_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_POS_S1_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_POS_S1_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_POS_S1_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT1_12 (number 6), POS_S2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_POS_S2_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_POS_S2_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_POS_S2_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_POS_S2_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_POS_S2_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_POS_S2_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT1_13 (number 7), POS_S3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_POS_S3_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_POS_S3_GPIO_PIN 13U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_POS_S3_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_POS_S3_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_POS_S3_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_POS_S3_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
